version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: rise_blog_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  rise-blog-service:
    build:
      context: ./rise-test
      dockerfile: Dockerfile
    container_name: rise-blog-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  pg-data:
