version: '3.8'

services:
  rise-blog-service:
    build:
      context: ./rise-test
      dockerfile: Dockerfile
    ports:
      - "40029:30029"
    stdin_open: true
    tty: true
    env_file:
      - ./rise-test/.env
    environment:
      - PSQL_DATABASE_PORT=5432
      - PSQL_DATABASE_HOST=postgres
      - PSQL_DATABASE_NAME=rise_blog_db
      - PSQL_DATABASE_USER=myuser
      - PSQL_DATABASE_PASSWORD=mypassword
      - HTTP_PORT=30029
      - SERVICE_NAME=riseBlogService
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: rise_blog_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
       - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  pg-data:
